#!/usr/bin/env php
<?php

/**
 * @file
 * Controller for the visual sitemap.
 */

use AKlump\LoftLib\Bash\Color;

define('ROOT', dirname(__FILE__));

try {
  require ROOT . '/includes/bootstrap.inc';
  $vismap->generate()->save();
}
catch (\Exception $exception) {
  echo Color::wrap('red', $exception->getMessage() . PHP_EOL);
  exit(1);
}
