#!/usr/bin/env php
<?php

/**
 * @file
 * Controller for the visual sitemap.
 */

use AKlump\LoftLib\Bash\Color;
use AKlump\LoftLib\Bash\Output;

define('ROOT', dirname(__FILE__));

try {
  require ROOT . '/includes/bootstrap.inc';
  $files_saved = $vismap->generate()->save();
}
catch (\Exception $exception) {
  echo Color::wrap('red', $exception->getMessage() . PHP_EOL);
  exit(1);
}

echo Color::wrap('green', 'Files created:'). PHP_EOL;
echo Output::list($files_saved);

exit(0);
